### ISSUE TITLE
Can you provide a way to prepare the env?

### ISSUE THREAD

**Issue by rayguan97** [fpthink/PPT-Net#6]
1. Have you seen this error before? Could you give some insight on what could happened? 
"""
cmd_str: cp ./models/pptnet.py exp/pptnet
Traceback (most recent call last):
  File "train.py", line 709, in <module>
    main()
  File "train.py", line 234, in main
    train(starting_epoch, model, optimizer, None, loss_function, lr_scheduler)
  File "train.py", line 241, in train
    train_one_epoch(model, optimizer, train_writer, loss_function, epoch)
  File "train.py", line 377, in train_one_epoch
    loss.backward()
  File "/home/anaconda3/envs/pptnet/lib/python3.6/site-packages/torch/tensor.py", line 195, in bac
kward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/anaconda3/envs/pptnet/lib/python3.6/site-packages/torch/autograd/__init__.py", line 
99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Expected isFloatingType(grads[i].type().scalarType()) to be true, but got false.  (Could thi
s error message be improved?  If so, please report an enhancement request to PyTorch.)

"""

2. Can you provide the original environment for this code? I can't have this code to work after tired in several environment.

**Comment by farawell** [comment]
Did you handle the environment issue?
